replicaCount: 3

image:
  repository: ghcr.io/sakshishukla013/gitops-app
  tag: "f8256ad7f938c469fc9526dfddf2ed0f8b4b971f"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

probes:
  readiness:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 10

  liveness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 20

securityContext:
  runAsNonRoot: true
  runAsUser: 1000