---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitops-app-secret
  namespace: gitops-app
spec:
  encryptedData:
    API_KEY: AgB2CM9h7qXdKaSUqHK9oKs55DTGPu5mTOwy+ECNgAHRsfZePvsxqoPDjlopUdZG9Wbw4IyrWH5gt3LZe3CzWoZW6gsYJ66MRILYSEXJplCdjwVub3y2j40v7c944M6ntZv8OFECQejg2CbAvotxPVA/cH0gOkM35WxQtubFTPCgPoZ7a7jxm6wwE9ngmqfzvjbSs0zP4To9gLtmPkt1tkjkKrzHIKFPsdvgjAZjEejjWOkv9xBjzUhKlV2o5OBHxnpX2sGHFQc9b3Um5BO7DgZ9TeaE2Ui0ouGg7Tl1xspaUQxTDlkhmfvONGIIcacCFIZ3MT0vUkAM7fgh5OcRuEk2L4lbTIob4Fz+bjaQ3dZfzjRWO/3y5qx++Pw02tabCrYyV+Os2v20h0/KfMZTvIJp/UVlgPm5OT/GL4cT0Fpw7Yb6NUxZn9BVFgEhQ119CzxcDqq97jYSR1/gm+PqWmUPD5qASmH5mt5nbp6F9AYcdaYlKaKVdFPnbltQnRRX4lmTHtib+1AA+qO6dxpe8GDRHurJ2vh29xhJ+7IFPb7iJMFafp0VQTiBbox033PoUgHAi4CMxSH2FSIgNIKDdayOMaIWt20A6uWKwtrbOd22NpwjTsAehnzzEbhYO/n52F8APHDpm25HOa1BM1Eprq4+pxUHBP3XLce7GiROAgim1xKW/x+cJ6j+xnBJ98Q9JynEe8ENCVmNrbTNuVYwZsA=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/tracking-id: gitops-app:/Secret:gitops-app/gitops-app-secret
      name: gitops-app-secret
      namespace: gitops-app
    type: Opaque
